# Generated by Django 3.1.7 on 2021-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_candlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_candregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(null=True)),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_candsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=10)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_compdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complid', models.CharField(default='', max_length=10, null=True)),
                ('jobtitle', models.CharField(max_length=50)),
                ('companyname', models.CharField(max_length=50)),
                ('companysite', models.CharField(max_length=50)),
                ('jobtype', models.CharField(max_length=50)),
                ('joblocation', models.CharField(max_length=50)),
                ('companydesc', models.CharField(max_length=500)),
                ('jobqualification', models.CharField(max_length=50)),
                ('joblink', models.CharField(max_length=50)),
                ('jobldate', models.DateField(max_length=50)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemail', models.EmailField(max_length=50)),
                ('lpassword', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_compregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remail', models.EmailField(max_length=50)),
                ('rpassword', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_jobsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jtitle', models.CharField(max_length=50)),
                ('jlocation', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
