# Generated by Django 3.1.7 on 2021-08-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_compdetails',
            name='jobldate',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
