# Generated by Django 3.1.7 on 2021-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20210812_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_compdetails',
            name='jobldate',
            field=models.DateField(null=True),
        ),
    ]
