# Generated by Django 3.1.7 on 2021-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20210812_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_compdetails',
            name='jobldate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
