# Generated by Django 3.1.7 on 2021-08-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20210812_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_compdetails',
            name='jobexperience',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
