# Generated by Django 3.1.7 on 2021-08-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_tbl_compdetails_jobexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_candregistration',
            name='cv',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
